import type { Job } from './types'

const now = new Date()
const ago = (days: number) =>
  new Date(now.getTime() - days * 86_400_000).toISOString()

export const MOCK_JOBS: Job[] = [
  // Operations
  {
    id: 'mock-ops-1',
    title: 'Data Center Operations Technician',
    company: 'Equinix',
    location: 'Ashburn, VA',
    category: 'operations',
    remote: false,
    description:
      'Perform hands-on data center operations including server installations, hardware replacements, power management, and facility maintenance. Work in a 24/7 mission-critical environment supporting hyperscale colocation infrastructure. You will be responsible for responding to critical alerts, conducting routine audits, and maintaining comprehensive documentation for all activities.',
    salary_min: 55000,
    salary_max: 72000,
    apply_target: 'https://equinix.com/careers',
    posted_by: null,
    created_at: ago(1),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-ops-2',
    title: 'Shift Lead, Critical Facilities',
    company: 'Iron Mountain',
    location: 'Dallas, TX',
    category: 'operations',
    remote: false,
    description:
      'Lead a team of data center technicians across 12-hour shifts in a Tier III colocation facility. Oversee all physical infrastructure operations including power distribution, cooling, and security systems. Champion safety and compliance programs while maintaining 99.999% uptime SLAs for Fortune 500 customers.',
    salary_min: 70000,
    salary_max: 90000,
    apply_target: 'https://ironmountain.com/careers',
    posted_by: null,
    created_at: ago(2),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-ops-3',
    title: 'Critical Facilities Manager',
    company: 'CyrusOne',
    location: 'Phoenix, AZ',
    category: 'operations',
    remote: false,
    description:
      'Manage day-to-day operations of a 150MW hyperscale campus including staff scheduling, vendor management, preventive maintenance programs, and capital project oversight. Partner with hyperscaler tenants to plan major infrastructure events and capacity expansions.',
    salary_min: 90000,
    salary_max: 115000,
    apply_target: 'https://cyrusone.com/careers',
    posted_by: null,
    created_at: ago(3),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-ops-4',
    title: 'Data Center Infrastructure Technician',
    company: 'QTS Data Centers',
    location: 'Atlanta, GA',
    category: 'operations',
    remote: false,
    description:
      'Support all aspects of data center operations including rack-and-stack deployments, remote hands services, cabling, and equipment decommissioning. Work closely with enterprise customers and cloud providers to execute change management procedures.',
    salary_min: 52000,
    salary_max: 68000,
    apply_target: 'https://qtsdatacenters.com/careers',
    posted_by: null,
    created_at: ago(5),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-ops-5',
    title: 'Senior Operations Engineer',
    company: 'Aligned Data Centers',
    location: 'Columbus, OH',
    category: 'operations',
    remote: false,
    description:
      'Drive operational excellence across a greenfield 80MW campus. Own critical infrastructure monitoring via DCIM tools, manage escalation procedures, and mentor junior technicians. Experience with BMS, EPMS, and CMMS platforms required.',
    salary_min: 85000,
    salary_max: 105000,
    apply_target: 'https://aligneddc.com/careers',
    posted_by: null,
    created_at: ago(7),
    status: 'active',
    paid_amount_cents: 9900,
  },

  // Construction
  {
    id: 'mock-con-1',
    title: 'Data Center Construction Manager',
    company: 'Turner Construction',
    location: 'Ashburn, VA',
    category: 'construction',
    remote: false,
    description:
      "Lead all on-site construction activities for a 32MW data center shell and core build. Manage subcontractors, track schedule and budget, and interface daily with the owner's project management team. OSHA 30 and experience with mission-critical construction required.",
    salary_min: 110000,
    salary_max: 145000,
    apply_target: 'https://turnerconstruction.com/careers',
    posted_by: null,
    created_at: ago(2),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-con-2',
    title: 'MEP Project Manager, Data Centers',
    company: 'JE Dunn Construction',
    location: 'Dallas, TX',
    category: 'construction',
    remote: false,
    description:
      'Coordinate mechanical, electrical, and plumbing scopes for large-scale data center construction projects. Review submittals, manage RFIs, and ensure commissioning readiness. Proficiency with Procore and Bluebeam required.',
    salary_min: 95000,
    salary_max: 125000,
    apply_target: 'https://jedunn.com/careers',
    posted_by: null,
    created_at: ago(4),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-con-3',
    title: 'Site Superintendent',
    company: 'Holder Construction',
    location: 'Atlanta, GA',
    category: 'construction',
    remote: false,
    description:
      'Direct daily field operations for a two-building data center campus including site logistics, safety programs, and quality control. Coordinate with MEP and structural subcontractors to maintain critical path schedule. 7+ years of commercial construction supervision required.',
    salary_min: 100000,
    salary_max: 130000,
    apply_target: 'https://holderconstruction.com/careers',
    posted_by: null,
    created_at: ago(6),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-con-4',
    title: 'Construction Project Engineer',
    company: 'Mortenson',
    location: 'Phoenix, AZ',
    category: 'construction',
    remote: false,
    description:
      'Support project managers on hyperscale data center construction with submittals, RFI management, schedule updates, and cost tracking. Opportunity to grow into a PM role within 2 years. Mission-critical or heavy commercial construction background preferred.',
    salary_min: 75000,
    salary_max: 95000,
    apply_target: 'https://mortenson.com/careers',
    posted_by: null,
    created_at: ago(10),
    status: 'active',
    paid_amount_cents: 9900,
  },

  // Electrical / Power
  {
    id: 'mock-elec-1',
    title: 'Critical Power Engineer',
    company: 'Schneider Electric',
    location: 'Ashburn, VA',
    category: 'electrical_power',
    remote: false,
    description:
      'Design and commission power distribution systems for new and existing data center facilities. Expertise in UPS systems, switchgear, PDUs, and generator sets required. Support customers with load bank testing, maintenance planning, and capacity studies.',
    salary_min: 95000,
    salary_max: 125000,
    apply_target: 'https://se.com/careers',
    posted_by: null,
    created_at: ago(1),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-elec-2',
    title: 'Power Systems Technician',
    company: 'Vertiv',
    location: 'Dallas, TX',
    category: 'electrical_power',
    remote: false,
    description:
      'Install, maintain, and repair UPS systems, PDUs, and transfer switches across a regional customer base. Travel up to 60% to data center sites. OSHA 30, NFPA 70E, and manufacturer certifications (APC, Vertiv, Eaton) preferred.',
    salary_min: 65000,
    salary_max: 85000,
    apply_target: 'https://vertiv.com/careers',
    posted_by: null,
    created_at: ago(3),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-elec-3',
    title: 'Electrical Engineer, Mission Critical',
    company: 'Eaton',
    location: 'Columbus, OH',
    category: 'electrical_power',
    remote: true,
    description:
      'Develop power system designs and technical proposals for hyperscale and enterprise data center projects. Create single-line diagrams, equipment specifications, and arc flash studies. PE license preferred; RCDD or BICSI credentials a plus.',
    salary_min: 100000,
    salary_max: 130000,
    apply_target: 'https://eaton.com/careers',
    posted_by: null,
    created_at: ago(5),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-elec-4',
    title: 'Generator Systems Specialist',
    company: 'Cummins',
    location: 'Atlanta, GA',
    category: 'electrical_power',
    remote: false,
    description:
      "Service and maintain diesel generator sets and automatic transfer switches for mission-critical data center customers. Perform warranty repairs, PM services, and emergency on-call response. Valid commercial driver's license and generator certifications required.",
    salary_min: 60000,
    salary_max: 80000,
    apply_target: 'https://cummins.com/careers',
    posted_by: null,
    created_at: ago(8),
    status: 'active',
    paid_amount_cents: 9900,
  },

  // Cooling / Mechanical
  {
    id: 'mock-cool-1',
    title: 'Cooling Infrastructure Lead',
    company: 'Switch',
    location: 'Las Vegas, NV',
    category: 'cooling_mechanical',
    remote: false,
    description:
      'Own the mechanical infrastructure strategy for Switch\'s SUPERNAP campus including chilled water systems, CRAC/CRAH units, cooling towers, and the patented SUPERCOOLING system. Drive PUE optimization and lead a team of 6 mechanical technicians.',
    salary_min: 95000,
    salary_max: 120000,
    apply_target: 'https://switch.com/careers',
    posted_by: null,
    created_at: ago(2),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-cool-2',
    title: 'HVAC Technician, Data Centers',
    company: 'Digital Realty',
    location: 'Atlanta, GA',
    category: 'cooling_mechanical',
    remote: false,
    description:
      'Maintain and repair HVAC and mechanical cooling equipment in a carrier-neutral colocation environment. Perform preventive maintenance on CRAC units, chillers, cooling towers, and associated controls. EPA 608 certification and 3+ years of commercial HVAC experience required.',
    salary_min: 58000,
    salary_max: 75000,
    apply_target: 'https://digitalrealty.com/careers',
    posted_by: null,
    created_at: ago(4),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-cool-3',
    title: 'Thermal Systems Engineer',
    company: 'Vantage Data Centers',
    location: 'Denver, CO',
    category: 'cooling_mechanical',
    remote: false,
    description:
      'Model and optimize thermal performance for Vantage\'s hyperscale campuses using CFD tools and DCIM data. Evaluate emerging cooling technologies including direct liquid cooling and rear-door heat exchangers. ASHRAE membership and PE license preferred.',
    salary_min: 100000,
    salary_max: 130000,
    apply_target: 'https://vantagedc.com/careers',
    posted_by: null,
    created_at: ago(9),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-cool-4',
    title: 'Mechanical Engineer, Critical Facilities',
    company: 'Stulz',
    location: 'Ashburn, VA',
    category: 'cooling_mechanical',
    remote: false,
    description:
      'Provide technical support and engineering services for Stulz precision cooling installations at hyperscale data centers across the Mid-Atlantic region. Develop commissioning plans, support startup activities, and deliver customer training.',
    salary_min: 80000,
    salary_max: 105000,
    apply_target: 'https://stulz.com/careers',
    posted_by: null,
    created_at: ago(11),
    status: 'active',
    paid_amount_cents: 9900,
  },

  // Networking
  {
    id: 'mock-net-1',
    title: 'Network Infrastructure Engineer',
    company: 'Meta',
    location: 'Menlo Park, CA',
    category: 'networking',
    remote: true,
    description:
      'Design and deploy physical network infrastructure for Meta\'s global data center fleet. Own fiber plant design, structured cabling standards, and cross-connect management. Experience with 400G optical networking and large-scale spine-leaf architectures required.',
    salary_min: 130000,
    salary_max: 175000,
    apply_target: 'https://metacareers.com',
    posted_by: null,
    created_at: ago(1),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-net-2',
    title: 'NOC Engineer',
    company: 'Lumen Technologies',
    location: 'Remote',
    category: 'networking',
    remote: true,
    description:
      'Monitor and respond to network events across Lumen\'s nationwide fiber and data center infrastructure. Manage tickets, coordinate with field teams, and execute escalation procedures for enterprise and government customers. CCNA or equivalent required.',
    salary_min: 65000,
    salary_max: 85000,
    apply_target: 'https://lumen.com/careers',
    posted_by: null,
    created_at: ago(3),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-net-3',
    title: 'Dark Fiber Network Technician',
    company: 'Zayo Group',
    location: 'Denver, CO',
    category: 'networking',
    remote: false,
    description:
      'Splice, test, and maintain dark fiber and DWDM infrastructure between data centers and carrier hotels across the Mountain West region. Perform OTDR testing, manage splice records in GIS, and respond to outages 24/7. Experience with Corning and OFS cable products preferred.',
    salary_min: 60000,
    salary_max: 78000,
    apply_target: 'https://zayo.com/careers',
    posted_by: null,
    created_at: ago(6),
    status: 'active',
    paid_amount_cents: 9900,
  },
  {
    id: 'mock-net-4',
    title: 'Cabling Infrastructure Lead',
    company: 'CommScope',
    location: 'Ashburn, VA',
    category: 'networking',
    remote: false,
    description:
      'Lead structured cabling deployments and upgrades in hyperscale and colocation data centers. Manage a team of 8 installers, maintain material inventory, and ensure all work meets TIA-942 standards. BICSI RCDD or DCDC certification required.',
    salary_min: 75000,
    salary_max: 95000,
    apply_target: 'https://commscope.com/careers',
    posted_by: null,
    created_at: ago(13),
    status: 'active',
    paid_amount_cents: 9900,
  },
]
